In [12]:
import pandas as pd
from datetime import datetime
import geopandas as gpd
from shapely.geometry import Point
import os

In [13]:
data = pd.read_excel("data/mean_center_combined.xlsx")

df = pd.DataFrame(data)

df

    id  year   latitude  longitude         type   icon
0    1  1790  39.885246 -75.165341  post office   star
1    1  1800  39.870022 -75.984666  post office   star
2    1  1810  39.895449 -76.899163  post office   star
3    1  1820  39.776280 -78.056850  post office   star
4    1  1830  39.600737 -78.964689  post office   star
5    1  1840  39.347771 -80.594858  post office   star
6    1  1850  39.185561 -81.799291  post office   star
7    1  1860  39.136415 -83.879322  post office   star
8    1  1870  39.506581 -84.747517  post office   star
9    1  1880  39.200004 -86.524739  post office   star
10   1  1890  38.909622 -87.346512  post office   star
11   1  1900  38.644614 -87.871008  post office   star
12   1  1910  38.823813 -89.569737  post office   star
13   1  1920  38.973996 -89.957022  post office   star
14   1  1930  39.041002 -89.994651  post office   star
15   1  1940  39.051373 -90.069575  post office   star
16   1  1950  39.065965 -90.013353  post office   star
17   1  1960  39.206138 -90.014776  post office   star
18   1  1970  39.196054 -89.999090  post office   star
19   1  1980  39.203106 -89.914743  post office   star
20   1  1990  39.188795 -89.943996  post office   star
21   1  2000  39.187219 -90.016598  post office   star
22   2  2000  37.696990 -91.809570   population  promo
23   2  1990  37.872220 -91.215280   population  promo
24   2  1980  38.136940 -90.573890   population  promo
25   2  1970  38.463060 -89.706110   population  promo
26   2  1960  38.599440 -89.209720   population  promo
27   2  1950  38.804170 -88.368890   population  promo
28   2  1940  38.948330 -87.376390   population  promo
29   2  1930  39.062500 -87.135000   population  promo
30   2  1920  39.172500 -86.720830   population  promo
31   2  1910  39.170000 -86.538890   population  promo
32   2  1900  39.160000 -85.815000   population  promo
33   2  1890  39.198890 -85.548060   population  promo
34   2  1880  39.068890 -84.661110   population  promo
35   2  1870  39.200000 -83.595000   population  promo
36   2  1860  39.006670 -82.813330   population  promo
37   2  1850  38.983330 -81.316670   population  promo
38   2  1840  39.033330 -80.300000   population  promo
39   2  1830  38.965000 -79.281670   population  promo
40   2  1820  39.095000 -78.550000   population  promo
41   2  1810  39.191670 -77.620000   population  promo
42   2  1800  39.268330 -76.941670   population  promo
43   2  1790  39.275000 -76.186670   population  promo

In [14]:
# create a GeoDataFrame from the DataFrame (df)
gdf_ = gpd.GeoDataFrame(df, 
                       # create a geometry column from longitude and latitude columns by converting them into points
                       geometry=gpd.points_from_xy(df.longitude, df.latitude),
                       # set the Coordinate Reference System (CRS) to EPSG:4326 (WGS 84 - geographic coordinate system)
                       crs="EPSG:4326") 

gdf_

,id,year,latitude,longitude,type,icon,geometry
0,1,1790,39.885246,-75.165341,post office,star,POINT (-75.16534 39.88525)
1,1,1800,39.870022,-75.984666,post office,star,POINT (-75.98467 39.87002)
2,1,1810,39.895449,-76.899163,post office,star,POINT (-76.89916 39.89545)
3,1,1820,39.776280,-78.056850,post office,star,POINT (-78.05685 39.77628)
4,1,1830,39.600737,-78.964689,post office,star,POINT (-78.96469 39.60074)
5,1,1840,39.347771,-80.594858,post office,star,POINT (-80.59486 39.34777)
6,1,1850,39.185561,-81.799291,post office,star,POINT (-81.79929 39.18556)
7,1,1860,39.136415,-83.879322,post office,star,POINT (-83.87932 39.13642)
8,1,1870,39.506581,-84.747517,post office,star,POINT (-84.74752 39.50658)
9,1,1880,39.200004,-86.524739,post office,star,POINT (-86.52474 39.2)
10,1,1890,38.909622,-87.346512,post office,star,POINT (-87.34651 38.90962)
11,1,1900,38.644614,-87.871008,post office,star,POINT (-87.87101 38.64461)
12,1,1910,38.823813,-89.569737,post office,star,POINT (-89.56974 38.82381)
13,1,1920,38.973996,-89.957022,post office,star,POINT (-89.95702 38.974)
14,1,1930,39.041002,-89.994651,post office,star,POINT (-89.99465 39.041)
15,1,1940,39.051373,-90.069575,post office,star,POINT (-90.06958 39.05137)
16,1,1950,39.065965,-90.013353,post office,star,POINT (-90.01335 39.06596)
17,1,1960,39.206138,-90.014776,post office,star,POINT (-90.01478 39.20614)
18,1,1970,39.196054,-89.999090,post office,star,POINT (-89.99909 39.19605)
19,1,1980,39.203106,-89.914743,post office,star,POINT (-89.91474 39.20311)
20,1,1990,39.188795,-89.943996,post office,star,POINT (-89.944 39.1888)
21,1,2000,39.187219,-90.016598,post office,star,POINT (-90.0166 39.18722)
22,2,2000,37.696990,-91.809570,population,promo,POINT (-91.80957 37.69699)
23,2,1990,37.872220,-91.215280,population,promo,POINT (-91.21528 37.87222)
24,2,1980,38.136940,-90.573890,population,promo,POINT (-90.57389 38.13694)
25,2,1970,38.463060,-89.706110,population,promo,POINT (-89.70611 38.46306)
26,2,1960,38.599440,-89.209720,population,promo,POINT (-89.20972 38.59944)
27,2,1950,38.804170,-88.368890,population,promo,POINT (-88.36889 38.80417)
28,2,1940,38.948330,-87.376390,population,promo,POINT (-87.37639 38.94833)
29,2,1930,39.062500,-87.135000,population,promo,POINT (-87.135 39.0625)
30,2,1920,39.172500,-86.720830,population,promo,POINT (-86.72083 39.1725)
31,2,1910,39.170000,-86.538890,population,promo,POINT (-86.53889 39.17)
32,2,1900,39.160000,-85.815000,population,promo,POINT (-85.815 39.16)
33,2,1890,39.198890,-85.548060,population,promo,POINT (-85.54806 39.19889)
34,2,1880,39.068890,-84.661110,population,promo,POINT (-84.66111 39.06889)
35,2,1870,39.200000,-83.595000,population,promo,POINT (-83.595 39.2)
36,2,1860,39.006670,-82.813330,population,promo,POINT (-82.81333 39.00667)
37,2,1850,38.983330,-81.316670,population,promo,POINT (-81.31667 38.98333)
38,2,1840,39.033330,-80.300000,population,promo,POINT (-80.3 39.03333)
39,2,1830,38.965000,-79.281670,population,promo,POINT (-79.28167 38.965)
40,2,1820,39.095000,-78.550000,population,promo,POINT (-78.55 39.095)
41,2,1810,39.191670,-77.620000,population,promo,POINT (-77.62 39.19167)
42,2,1800,39.268330,-76.941670,population,promo,POINT (-76.94167 39.26833)
43,2,1790,39.275000,-76.186670,population,promo,POINT (-76.18667 39.275)

In [15]:
gdf = gpd.read_file("data/counties_states_combined_simplified.geojson")

gdf.head(10)

,STATE_COUNTY,STATE,CWA,COUNTYNAME,FIPS,TIME_ZONE,FE_AREA,LON,LAT,geometry
0,AK_Aleutians East,AK,AFC,Aleutians East,02013,A,None,-161.8631,55.4039,"MULTIPOLYGON (((-162.45576 54.36005, -162.4963..."
1,AK_Aleutians West,AK,AFC,Aleutians West,02016,Ah,None,-111.2564,52.8883,"MULTIPOLYGON (((-179.08545 51.29422, -179.0581..."
2,AK_Anchorage,AK,AFC,Anchorage,02020,A,None,-149.1067,61.1501,"MULTIPOLYGON (((-149.2379 61.45531, -149.1876 ..."
3,AK_Bethel,AK,AFC,Bethel,02050,A,None,-159.7733,60.9210,"MULTIPOLYGON (((-166.10333 59.83039, -166.107 ..."
4,AK_Bristol Bay,AK,AFC,Bristol Bay,02060,A,None,-156.7013,58.7423,"POLYGON ((-156.31814 58.89495, -156.31767 58.6..."
5,AK_Chugach,AK,AFC,Chugach,02063,A,None,-145.7950,60.7357,"MULTIPOLYGON (((-147.81645 60.06182, -147.8676..."
6,AK_Copper River,AK,AFC,Copper River,02066,A,None,-143.9685,61.8844,"POLYGON ((-145.1489 63.22221, -145.1484 63.133..."
7,AK_Denali,AK,AFG,Denali,02068,A,None,-150.0083,63.6739,"POLYGON ((-150.7497 64.36511, -147.9969 64.341..."
8,AK_Dillingham,AK,AFC,Dillingham,02070,A,None,-158.2119,59.8021,"MULTIPOLYGON (((-159.97017 58.61057, -159.9606..."
9,AK_Fairbanks North Star,AK,AFG,Fairbanks North Star,02090,A,None,-146.5630,64.8084,"POLYGON ((-146.1646 65.44291, -146.1123 65.403..."

In [16]:
gdf = gdf.to_crs(epsg=4326)

print(gdf.crs)

EPSG:4326

In [17]:
gdf = gdf[['COUNTYNAME','STATE', 'geometry']]

gdf['COUNTYNAME'] = gdf['COUNTYNAME'].str.upper()

gdf

          COUNTYNAME STATE                                           geometry
0     ALEUTIANS EAST    AK  MULTIPOLYGON (((-162.45576 54.36005, -162.4963...
1     ALEUTIANS WEST    AK  MULTIPOLYGON (((-179.08545 51.29422, -179.0581...
2          ANCHORAGE    AK  MULTIPOLYGON (((-149.2379 61.45531, -149.1876 ...
3             BETHEL    AK  MULTIPOLYGON (((-166.10333 59.83039, -166.107 ...
4        BRISTOL BAY    AK  POLYGON ((-156.31814 58.89495, -156.31767 58.6...
...              ...   ...                                                ...
3279      SWEETWATER    WY  POLYGON ((-109.7512 42.26571, -107.5227 42.261...
3280           TETON    WY  POLYGON ((-110.7457 44.66641, -110.6679 44.666...
3281           UINTA    WY  POLYGON ((-110.9245 41.57921, -110.048 41.5774...
3282        WASHAKIE    WY  POLYGON ((-107.87469 44.16821, -107.1286 44.16...
3283          WESTON    WY  POLYGON ((-104.4772 44.18061, -104.0545 44.180...

[3284 rows x 3 columns]

In [ ]:
# perform a spatial join between the GeoDataFrame 'gdf_' and another GeoDataFrame 'gdf' 
# using the 'intersects' predicate to match geometries that intersect. This operation adds 
# columns from 'gdf' to 'gdf_' where the geometries overlap.
mean_center_with_counties = gpd.sjoin(gdf_, gdf, how="left", predicate="intersects")

# select specific columns from the resulting GeoDataFrame ('mean_center_with_counties')
# the columns are 'id', 'year', 'latitude', 'icon', 'type', 'longitude', 'COUNTYNAME', and 'STATE'.
mean_center_with_counties = mean_center_with_counties[['id', 'year', 'latitude', 'icon', 'type', 'longitude', 'COUNTYNAME', 'STATE']]

mean_center_with_counties

    id  year   latitude   icon         type  longitude    COUNTYNAME STATE
0    1  1790  39.885246   star  post office -75.165341  PHILADELPHIA    PA
1    1  1800  39.870022   star  post office -75.984666       CHESTER    PA
2    1  1810  39.895449   star  post office -76.899163          YORK    PA
3    1  1820  39.776280   star  post office -78.056850        FULTON    PA
4    1  1830  39.600737   star  post office -78.964689      ALLEGANY    MD
5    1  1840  39.347771   star  post office -80.594858     DODDRIDGE    WV
6    1  1850  39.185561   star  post office -81.799291        ATHENS    OH
7    1  1860  39.136415   star  post office -83.879322         BROWN    OH
8    1  1870  39.506581   star  post office -84.747517        BUTLER    OH
9    1  1880  39.200004   star  post office -86.524739        MONROE    IN
10   1  1890  38.909622   star  post office -87.346512      SULLIVAN    IN
11   1  1900  38.644614   star  post office -87.871008      LAWRENCE    IL
12   1  1910  38.823813   star  post office -89.569737          BOND    IL
13   1  1920  38.973996   star  post office -89.957022       MADISON    IL
14   1  1930  39.041002   star  post office -89.994651      MACOUPIN    IL
15   1  1940  39.051373   star  post office -90.069575      MACOUPIN    IL
16   1  1950  39.065965   star  post office -90.013353      MACOUPIN    IL
17   1  1960  39.206138   star  post office -90.014776      MACOUPIN    IL
18   1  1970  39.196054   star  post office -89.999090      MACOUPIN    IL
19   1  1980  39.203106   star  post office -89.914743      MACOUPIN    IL
20   1  1990  39.188795   star  post office -89.943996      MACOUPIN    IL
21   1  2000  39.187219   star  post office -90.016598      MACOUPIN    IL
22   2  2000  37.696990  promo   population -91.809570        PHELPS    MO
23   2  1990  37.872220  promo   population -91.215280      CRAWFORD    MO
24   2  1980  38.136940  promo   population -90.573890     JEFFERSON    MO
25   2  1970  38.463060  promo   population -89.706110     ST. CLAIR    IL
26   2  1960  38.599440  promo   population -89.209720       CLINTON    IL
27   2  1950  38.804170  promo   population -88.368890          CLAY    IL
28   2  1940  38.948330  promo   population -87.376390      SULLIVAN    IN
29   2  1930  39.062500  promo   population -87.135000        GREENE    IN
30   2  1920  39.172500  promo   population -86.720830          OWEN    IN
31   2  1910  39.170000  promo   population -86.538890        MONROE    IN
32   2  1900  39.160000  promo   population -85.815000   BARTHOLOMEW    IN
33   2  1890  39.198890  promo   population -85.548060       DECATUR    IN
34   2  1880  39.068890  promo   population -84.661110         BOONE    KY
35   2  1870  39.200000  promo   population -83.595000      HIGHLAND    OH
36   2  1860  39.006670  promo   population -82.813330          PIKE    OH
37   2  1850  38.983330  promo   population -81.316670          WIRT    WV
38   2  1840  39.033330  promo   population -80.300000        UPSHUR    WV
39   2  1830  38.965000  promo   population -79.281670         GRANT    WV
40   2  1820  39.095000  promo   population -78.550000         HARDY    WV
41   2  1810  39.191670  promo   population -77.620000       LOUDOUN    VA
42   2  1800  39.268330  promo   population -76.941670        HOWARD    MD
43   2  1790  39.275000  promo   population -76.186670          KENT    MD

In [ ]:
# create a new column 'datetime' by converting the 'year' column to a string and combining it with a fixed date
# ('-01-01 00:01:00') to represent the first day of each year at midnight.
mean_center_with_counties['datetime'] = pd.to_datetime(mean_center_with_counties['year'].astype(str) + '-01-01 00:01:00')

# sort the data by 'id' and 'year' to ensure the correct order for further processing.
mean_center_with_counties = mean_center_with_counties.sort_values(by=['id', 'year'])

# add new columns directly to the original DataFrame:
# - 'source lat' and 'source lng' hold the latitude and longitude values.
mean_center_with_counties['source lat'] = mean_center_with_counties['latitude']
mean_center_with_counties['source lng'] = mean_center_with_counties['longitude']

# - 'target lat' and 'target lng' hold the next latitude and longitude for each 'id' based on the group,
#   using the shift function to access the next row's latitude and longitude for each 'id' group.
mean_center_with_counties['target lat'] = mean_center_with_counties.groupby('id')['latitude'].shift(-1)  # Next latitude
mean_center_with_counties['target lng'] = mean_center_with_counties.groupby('id')['longitude'].shift(-1)  # Next longitude

# fill the 'target lat' and 'target lng' columns with NaN for the last year of each group, as there is no subsequent year.
mean_center_with_counties.loc[mean_center_with_counties['year'] == 2000, ['target lat', 'target lng']] = None

# display the updated DataFrame
mean_center_with_counties

,id,year,latitude,icon,type,longitude,COUNTYNAME,STATE,datetime,source lat,source lng,target lat,target lng
0,1,1790,39.885246,star,post office,-75.165341,PHILADELPHIA,PA,1790-01-01 00:01:00,39.885246,-75.165341,39.870022,-75.984666
1,1,1800,39.870022,star,post office,-75.984666,CHESTER,PA,1800-01-01 00:01:00,39.870022,-75.984666,39.895449,-76.899163
2,1,1810,39.895449,star,post office,-76.899163,YORK,PA,1810-01-01 00:01:00,39.895449,-76.899163,39.776280,-78.056850
3,1,1820,39.776280,star,post office,-78.056850,FULTON,PA,1820-01-01 00:01:00,39.776280,-78.056850,39.600737,-78.964689
4,1,1830,39.600737,star,post office,-78.964689,ALLEGANY,MD,1830-01-01 00:01:00,39.600737,-78.964689,39.347771,-80.594858
5,1,1840,39.347771,star,post office,-80.594858,DODDRIDGE,WV,1840-01-01 00:01:00,39.347771,-80.594858,39.185561,-81.799291
6,1,1850,39.185561,star,post office,-81.799291,ATHENS,OH,1850-01-01 00:01:00,39.185561,-81.799291,39.136415,-83.879322
7,1,1860,39.136415,star,post office,-83.879322,BROWN,OH,1860-01-01 00:01:00,39.136415,-83.879322,39.506581,-84.747517
8,1,1870,39.506581,star,post office,-84.747517,BUTLER,OH,1870-01-01 00:01:00,39.506581,-84.747517,39.200004,-86.524739
9,1,1880,39.200004,star,post office,-86.524739,MONROE,IN,1880-01-01 00:01:00,39.200004,-86.524739,38.909622,-87.346512
10,1,1890,38.909622,star,post office,-87.346512,SULLIVAN,IN,1890-01-01 00:01:00,38.909622,-87.346512,38.644614,-87.871008
11,1,1900,38.644614,star,post office,-87.871008,LAWRENCE,IL,1900-01-01 00:01:00,38.644614,-87.871008,38.823813,-89.569737
12,1,1910,38.823813,star,post office,-89.569737,BOND,IL,1910-01-01 00:01:00,38.823813,-89.569737,38.973996,-89.957022
13,1,1920,38.973996,star,post office,-89.957022,MADISON,IL,1920-01-01 00:01:00,38.973996,-89.957022,39.041002,-89.994651
14,1,1930,39.041002,star,post office,-89.994651,MACOUPIN,IL,1930-01-01 00:01:00,39.041002,-89.994651,39.051373,-90.069575
15,1,1940,39.051373,star,post office,-90.069575,MACOUPIN,IL,1940-01-01 00:01:00,39.051373,-90.069575,39.065965,-90.013353
16,1,1950,39.065965,star,post office,-90.013353,MACOUPIN,IL,1950-01-01 00:01:00,39.065965,-90.013353,39.206138,-90.014776
17,1,1960,39.206138,star,post office,-90.014776,MACOUPIN,IL,1960-01-01 00:01:00,39.206138,-90.014776,39.196054,-89.999090
18,1,1970,39.196054,star,post office,-89.999090,MACOUPIN,IL,1970-01-01 00:01:00,39.196054,-89.999090,39.203106,-89.914743
19,1,1980,39.203106,star,post office,-89.914743,MACOUPIN,IL,1980-01-01 00:01:00,39.203106,-89.914743,39.188795,-89.943996
20,1,1990,39.188795,star,post office,-89.943996,MACOUPIN,IL,1990-01-01 00:01:00,39.188795,-89.943996,39.187219,-90.016598
21,1,2000,39.187219,star,post office,-90.016598,MACOUPIN,IL,2000-01-01 00:01:00,39.187219,-90.016598,NaN,NaN
43,2,1790,39.275000,promo,population,-76.186670,KENT,MD,1790-01-01 00:01:00,39.275000,-76.186670,39.268330,-76.941670
42,2,1800,39.268330,promo,population,-76.941670,HOWARD,MD,1800-01-01 00:01:00,39.268330,-76.941670,39.191670,-77.620000
41,2,1810,39.191670,promo,population,-77.620000,LOUDOUN,VA,1810-01-01 00:01:00,39.191670,-77.620000,39.095000,-78.550000
40,2,1820,39.095000,promo,population,-78.550000,HARDY,WV,1820-01-01 00:01:00,39.095000,-78.550000,38.965000,-79.281670
39,2,1830,38.965000,promo,population,-79.281670,GRANT,WV,1830-01-01 00:01:00,38.965000,-79.281670,39.033330,-80.300000
38,2,1840,39.033330,promo,population,-80.300000,UPSHUR,WV,1840-01-01 00:01:00,39.033330,-80.300000,38.983330,-81.316670
37,2,1850,38.983330,promo,population,-81.316670,WIRT,WV,1850-01-01 00:01:00,38.983330,-81.316670,39.006670,-82.813330
36,2,1860,39.006670,promo,population,-82.813330,PIKE,OH,1860-01-01 00:01:00,39.006670,-82.813330,39.200000,-83.595000
35,2,1870,39.200000,promo,population,-83.595000,HIGHLAND,OH,1870-01-01 00:01:00,39.200000,-83.595000,39.068890,-84.661110
34,2,1880,39.068890,promo,population,-84.661110,BOONE,KY,1880-01-01 00:01:00,39.068890,-84.661110,39.198890,-85.548060
33,2,1890,39.198890,promo,population,-85.548060,DECATUR,IN,1890-01-01 00:01:00,39.198890,-85.548060,39.160000,-85.815000
32,2,1900,39.160000,promo,population,-85.815000,BARTHOLOMEW,IN,1900-01-01 00:01:00,39.160000,-85.815000,39.170000,-86.538890
31,2,1910,39.170000,promo,population,-86.538890,MONROE,IN,1910-01-01 00:01:00,39.170000,-86.538890,39.172500,-86.720830
30,2,1920,39.172500,promo,population,-86.720830,OWEN,IN,1920-01-01 00:01:00,39.172500,-86.720830,39.062500,-87.135000
29,2,1930,39.062500,promo,population,-87.135000,GREENE,IN,1930-01-01 00:01:00,39.062500,-87.135000,38.948330,-87.376390
28,2,1940,38.948330,promo,population,-87.376390,SULLIVAN,IN,1940-01-01 00:01:00,38.948330,-87.376390,38.804170,-88.368890
27,2,1950,38.804170,promo,population,-88.368890,CLAY,IL,1950-01-01 00:01:00,38.804170,-88.368890,38.599440,-89.209720
26,2,1960,38.599440,promo,population,-89.209720,CLINTON,IL,1960-01-01 00:01:00,38.599440,-89.209720,38.463060,-89.706110
25,2,1970,38.463060,promo,population,-89.706110,ST. CLAIR,IL,1970-01-01 00:01:00,38.463060,-89.706110,38.136940,-90.573890
24,2,1980,38.136940,promo,population,-90.573890,JEFFERSON,MO,1980-01-01 00:01:00,38.136940,-90.573890,37.872220,-91.215280
23,2,1990,37.872220,promo,population,-91.215280,CRAWFORD,MO,1990-01-01 00:01:00,37.872220,-91.215280,37.696990,-91.809570
22,2,2000,37.696990,promo,population,-91.809570,PHELPS,MO,2000-01-01 00:01:00,37.696990,-91.809570,NaN,NaN

In [10]:
csv_path = "routes_data_mean_center.csv"
excel_path = "routes_data_mean_center.xlsx"

mean_center_with_counties.to_csv(csv_path, index=False)
mean_center_with_counties.to_excel(excel_path, index=False)